/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ass1_2;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class AddressBookForm extends javax.swing.JFrame {

    /**
     * Creates new form AddressBookForm
     */
    public AddressBookForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblHomeAddress = new javax.swing.JLabel();
        lblHomePhoneno = new javax.swing.JLabel();
        txtHomePhoneno = new javax.swing.JTextField();
        lblBusinessAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHomeAddress = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBusinessAddress = new javax.swing.JTextArea();
        lblBusinessPhoneno = new javax.swing.JLabel();
        txtBusinessPhoneno = new javax.swing.JTextField();
        lblFaxMachieno = new javax.swing.JLabel();
        txtFaxMachineno = new javax.swing.JTextField();
        lblCellularPhoneno = new javax.swing.JLabel();
        txtCellularPhoneno = new javax.swing.JTextField();
        lblPagerno = new javax.swing.JLabel();
        txtPagerno = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        AddressBookTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setText("Name:");
        lblName.setName("lblName"); // NOI18N

        txtName.setName("txtName"); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblHomeAddress.setText("Home Address:");
        lblHomeAddress.setName("lblHomeAddress"); // NOI18N

        lblHomePhoneno.setText("Home Phoneno:");
        lblHomePhoneno.setName("lblHomePhoneno"); // NOI18N

        txtHomePhoneno.setName("txtHomePhoneno"); // NOI18N
        txtHomePhoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomePhonenoActionPerformed(evt);
            }
        });

        lblBusinessAddress.setText("Business Address:");
        lblBusinessAddress.setName("lblHomePhoneno"); // NOI18N

        txtHomeAddress.setColumns(20);
        txtHomeAddress.setRows(5);
        jScrollPane1.setViewportView(txtHomeAddress);

        jScrollPane2.setName("txtBusinessAddress"); // NOI18N

        txtBusinessAddress.setColumns(20);
        txtBusinessAddress.setRows(5);
        jScrollPane2.setViewportView(txtBusinessAddress);

        lblBusinessPhoneno.setText("Business Phoneno:");

        txtBusinessPhoneno.setName("txtBusinessPhoneno"); // NOI18N

        lblFaxMachieno.setText("Fax Machine Number:");
        lblFaxMachieno.setName("lblFaxMachineNumber"); // NOI18N

        txtFaxMachineno.setName("txtFaxMachineNumber"); // NOI18N

        lblCellularPhoneno.setText("Cellular Phone No:");
        lblCellularPhoneno.setName("lblCellularPhoneno"); // NOI18N

        txtCellularPhoneno.setName("txtCellularPhoneno"); // NOI18N

        lblPagerno.setText("Page Number:");
        lblPagerno.setName("lblPageNumber"); // NOI18N

        txtPagerno.setName("txtPagerNumber"); // NOI18N
        txtPagerno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagernoActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.setName("btnEdit"); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        AddressBookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Home Address", "Home Phoneno", "Buiseness Address", "Business Phoneno", "Fax Machineno", "Cellular Phoneno", "Pagerno"
            }
        ));
        AddressBookTable.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                AddressBookTableMouseWheelMoved(evt);
            }
        });
        AddressBookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddressBookTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(AddressBookTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblPagerno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCellularPhoneno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFaxMachieno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBusinessPhoneno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHomePhoneno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBusinessAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCellularPhoneno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFaxMachineno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBusinessPhoneno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtHomePhoneno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPagerno))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblHomeAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomePhoneno)
                    .addComponent(txtHomePhoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblBusinessAddress))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusinessPhoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusinessPhoneno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxMachieno)
                    .addComponent(txtFaxMachineno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCellularPhoneno)
                    .addComponent(txtCellularPhoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagerno)
                    .addComponent(txtPagerno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<AddressBook> addressBookList = new ArrayList<AddressBook>();
    
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtHomePhonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomePhonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomePhonenoActionPerformed

    private void txtPagernoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagernoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagernoActionPerformed

    private void refreshForm()
    {
        txtName.setText("");
        txtHomeAddress.setText("");
        txtHomePhoneno.setText("");
        txtBusinessAddress.setText("");
        txtBusinessPhoneno.setText("");
        txtFaxMachineno.setText("");
        txtCellularPhoneno.setText("");
        txtPagerno.setText("");
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String pname = txtName.getText();
        String hAddress = txtHomeAddress.getText();
        String hPhoneno = txtHomePhoneno.getText();
        String bAddress = txtBusinessAddress.getText();
        String bPhoneno = txtBusinessPhoneno.getText();
        String fMachineno = txtFaxMachineno.getText();
        String cPhoneno = txtCellularPhoneno.getText();
        String pno = txtPagerno.getText();
        
        addressBookList.add(new AddressBook(pname, hAddress, hPhoneno, bAddress, bPhoneno, fMachineno, cPhoneno, pno));
        
        DefaultTableModel dtblModel = (DefaultTableModel)AddressBookTable.getModel();
        String addressBook[] = {pname, hAddress, hPhoneno, bAddress, bPhoneno, fMachineno, cPhoneno, pno};
        dtblModel.addRow(addressBook);
        
        refreshForm();
        
        JOptionPane.showMessageDialog(this, "Data Added Successfully!!");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtblModel = (DefaultTableModel)AddressBookTable.getModel();
        if(AddressBookTable.getSelectedRowCount() == 1){
            String pname = txtName.getText();
            String hAddress = txtHomeAddress.getText();
            String hPhoneno = txtHomePhoneno.getText();
            String bAddress = txtBusinessAddress.getText();
            String bPhoneno = txtBusinessPhoneno.getText();
            String fMachineno = txtFaxMachineno.getText();
            String cPhoneno = txtCellularPhoneno.getText();
            String pno = txtPagerno.getText();
            
            dtblModel.setValueAt(pname, AddressBookTable.getSelectedRow(), 0);
            dtblModel.setValueAt(hAddress, AddressBookTable.getSelectedRow(), 1);
            dtblModel.setValueAt(hPhoneno, AddressBookTable.getSelectedRow(), 2);
            dtblModel.setValueAt(bAddress, AddressBookTable.getSelectedRow(), 3);
            dtblModel.setValueAt(bPhoneno, AddressBookTable.getSelectedRow(), 4);
            dtblModel.setValueAt(fMachineno, AddressBookTable.getSelectedRow(), 5);
            dtblModel.setValueAt(cPhoneno, AddressBookTable.getSelectedRow(), 6);
            dtblModel.setValueAt(pno, AddressBookTable.getSelectedRow(), 7);
            
            AddressBook data = addressBookList.stream().filter(obj -> obj.pname.equals(pname)).findAny().orElse(null);
            int updateIndex = addressBookList.indexOf(data);
            addressBookList.set(updateIndex, new AddressBook(pname, hAddress, hPhoneno, bAddress, bPhoneno, fMachineno, cPhoneno, pno));
            
            refreshForm();
            
            JOptionPane.showMessageDialog(this, "Data Updated Successfully!!");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtblModel = (DefaultTableModel)AddressBookTable.getModel();
        if(AddressBookTable.getSelectedRowCount() == 1){
            String pname = txtName.getText();
            AddressBook data = addressBookList.stream().filter(obj -> obj.pname.equals(pname)).findAny().orElse(null);
            addressBookList.remove(data);
            dtblModel.removeRow(AddressBookTable.getSelectedRow());
            JOptionPane.showMessageDialog(this, "Data Deleted Successfully!!");
        }
        refreshForm();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        refreshForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void AddressBookTableMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_AddressBookTableMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressBookTableMouseWheelMoved

    private void AddressBookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddressBookTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtblModel = (DefaultTableModel)AddressBookTable.getModel();
        
        txtName.setText(dtblModel.getValueAt(AddressBookTable.getSelectedRow(), 0).toString());
        txtHomeAddress.setText(dtblModel.getValueAt(AddressBookTable.getSelectedRow(), 1).toString());
        txtHomePhoneno.setText(dtblModel.getValueAt(AddressBookTable.getSelectedRow(), 2).toString());
        txtBusinessAddress.setText(dtblModel.getValueAt(AddressBookTable.getSelectedRow(), 3).toString());
        txtBusinessPhoneno.setText(dtblModel.getValueAt(AddressBookTable.getSelectedRow(), 4).toString());
        txtFaxMachineno.setText(dtblModel.getValueAt(AddressBookTable.getSelectedRow(), 5).toString());
        txtCellularPhoneno.setText(dtblModel.getValueAt(AddressBookTable.getSelectedRow(), 6).toString());
        txtPagerno.setText(dtblModel.getValueAt(AddressBookTable.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_AddressBookTableMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddressBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddressBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddressBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddressBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddressBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AddressBookTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBusinessAddress;
    private javax.swing.JLabel lblBusinessPhoneno;
    private javax.swing.JLabel lblCellularPhoneno;
    private javax.swing.JLabel lblFaxMachieno;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblHomePhoneno;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPagerno;
    private javax.swing.JTextArea txtBusinessAddress;
    private javax.swing.JTextField txtBusinessPhoneno;
    private javax.swing.JTextField txtCellularPhoneno;
    private javax.swing.JTextField txtFaxMachineno;
    private javax.swing.JTextArea txtHomeAddress;
    private javax.swing.JTextField txtHomePhoneno;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPagerno;
    // End of variables declaration//GEN-END:variables
}
