/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ass1_5;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.Connection;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class RetailCompanyForm extends javax.swing.JFrame {
    private static Connection con;
    private static PreparedStatement pstmt;
    private static String qry;
    /**
     * Creates new form RetailCompanyForm
     */
    public RetailCompanyForm() {
        initComponents();
        DisplayData();
        GetAverageIncome();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblHomeAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHomeAddress = new javax.swing.JTextArea();
        lblHomePhoneno = new javax.swing.JLabel();
        txtHomePhoneno = new javax.swing.JTextField();
        lblBusinessAddress = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBusinessAddress = new javax.swing.JTextArea();
        lblBusinessPhoneno = new javax.swing.JLabel();
        txtBusinessPhoneno = new javax.swing.JTextField();
        lblFaxMachineno = new javax.swing.JLabel();
        txtFaxMachineno = new javax.swing.JTextField();
        lblCellularPhoneno = new javax.swing.JLabel();
        lblPagerno = new javax.swing.JLabel();
        txtPagerno = new javax.swing.JTextField();
        txtCellularPhoneno = new javax.swing.JTextField();
        lblMaritalStatus = new javax.swing.JLabel();
        cbxMaritalStatus = new javax.swing.JComboBox<>();
        lblNoofChildren = new javax.swing.JLabel();
        txtNoofChildren = new javax.swing.JTextField();
        lblAnnualIncome = new javax.swing.JLabel();
        txtAnnualIncome = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        RetailCompanyTable = new javax.swing.JTable();
        lblAverageIncome = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtAverageIncome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblName.setText("Name:");

        lblHomeAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHomeAddress.setText("Home Address:");

        txtHomeAddress.setColumns(20);
        txtHomeAddress.setRows(5);
        jScrollPane1.setViewportView(txtHomeAddress);

        lblHomePhoneno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHomePhoneno.setText("Home Phoneno:");

        lblBusinessAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBusinessAddress.setText("Business Address:");

        txtBusinessAddress.setColumns(20);
        txtBusinessAddress.setRows(5);
        jScrollPane3.setViewportView(txtBusinessAddress);

        lblBusinessPhoneno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBusinessPhoneno.setText("Business Phoneno:");

        lblFaxMachineno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFaxMachineno.setText("Fax Machineno:");

        lblCellularPhoneno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCellularPhoneno.setText("Cellular Phoneno:");

        lblPagerno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPagerno.setText("Pager No:");

        lblMaritalStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaritalStatus.setText("Merital Status:");

        cbxMaritalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced" }));

        lblNoofChildren.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNoofChildren.setText("No of children:");

        lblAnnualIncome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnnualIncome.setText("Annual Income:");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        RetailCompanyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Home Address", "Home Phoneno", "Business Address", "Business Phoneno", "Fax Machineno", "Cellular Phoneno", "Pager no", "Merital Status", "No of Children", "Annual Income"
            }
        ));
        RetailCompanyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetailCompanyTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(RetailCompanyTable);

        lblAverageIncome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAverageIncome.setText("Average Income of Married People:");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtAverageIncome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAnnualIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnnualIncome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxMaritalStatus, 0, 202, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBusinessPhoneno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusinessPhoneno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCellularPhoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCellularPhoneno))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHomeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtName))))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBusinessAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHomePhoneno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPagerno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFaxMachineno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNoofChildren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtHomePhoneno, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(txtFaxMachineno, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPagerno, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoofChildren, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAverageIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAverageIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHomePhoneno)
                    .addComponent(txtHomePhoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblBusinessAddress))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblHomeAddress)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusinessPhoneno)
                    .addComponent(txtBusinessPhoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFaxMachineno)
                    .addComponent(txtFaxMachineno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCellularPhoneno)
                    .addComponent(lblPagerno)
                    .addComponent(txtPagerno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCellularPhoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaritalStatus)
                    .addComponent(cbxMaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoofChildren)
                    .addComponent(txtNoofChildren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnnualIncome)
                    .addComponent(txtAnnualIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAverageIncome)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(txtAverageIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
            pstmt = con.prepareStatement("insert into retailcompany values(?,?,?,?,?,?,?,?,?,?,?)");
            pstmt.setString(1, txtName.getText());
            pstmt.setString(2, txtHomeAddress.getText());
            pstmt.setString(3, txtHomePhoneno.getText());
            pstmt.setString(4, txtBusinessAddress.getText());
            pstmt.setString(5, txtBusinessPhoneno.getText());
            pstmt.setString(6, txtFaxMachineno.getText());
            pstmt.setString(7, txtCellularPhoneno.getText());
            pstmt.setString(8, txtPagerno.getText());
            pstmt.setString(9, cbxMaritalStatus.getSelectedItem().toString());
            pstmt.setInt(10, Integer.parseInt(txtNoofChildren.getText()));
            pstmt.setInt(11, Integer.parseInt(txtAnnualIncome.getText()));
            
            pstmt.executeUpdate();
            DisplayData();
            GetAverageIncome();
            refreshForm();
            JOptionPane.showMessageDialog(this, "Data Added Successfully!!");
            
            
        } catch(Exception ex){
            Logger.getLogger(RetailCompanyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void RetailCompanyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetailCompanyTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)RetailCompanyTable.getModel();
        
        txtName.setText(tblModel.getValueAt(RetailCompanyTable.getSelectedRow(), 0).toString());
        txtHomeAddress.setText(tblModel.getValueAt(RetailCompanyTable.getSelectedRow(), 1).toString());
        txtHomePhoneno.setText(tblModel.getValueAt(RetailCompanyTable.getSelectedRow(), 2).toString());
        txtBusinessAddress.setText(tblModel.getValueAt(RetailCompanyTable.getSelectedRow(), 3).toString());
        txtBusinessPhoneno.setText(tblModel.getValueAt(RetailCompanyTable.getSelectedRow(), 4).toString());
        txtFaxMachineno.setText(tblModel.getValueAt(RetailCompanyTable.getSelectedRow(), 5).toString());
        txtCellularPhoneno.setText(tblModel.getValueAt(RetailCompanyTable.getSelectedRow(), 6).toString());
        txtPagerno.setText(tblModel.getValueAt(RetailCompanyTable.getSelectedRow(), 7).toString());
        cbxMaritalStatus.setSelectedItem(tblModel.getValueAt(RetailCompanyTable.getSelectedRow(), 8).toString());
        txtNoofChildren.setText(tblModel.getValueAt(RetailCompanyTable.getSelectedRow(), 9).toString());
        txtAnnualIncome.setText(tblModel.getValueAt(RetailCompanyTable.getSelectedRow(), 10).toString());
    }//GEN-LAST:event_RetailCompanyTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            qry = "update retailcompany set home_address=?, home_phoneno=?,business_address=?,business_phoneno=?,faxmachineno=?,cellular_phoneno=?,pagerno=?,merital_status=?,no_of_childern=?,annual_income=? where name=?";
            pstmt = con.prepareStatement(qry);
            pstmt.setString(1, txtHomeAddress.getText());
            pstmt.setString(2, txtHomePhoneno.getText());
            pstmt.setString(3, txtBusinessAddress.getText());
            pstmt.setString(4, txtBusinessPhoneno.getText());
            pstmt.setString(5, txtFaxMachineno.getText());
            pstmt.setString(6, txtCellularPhoneno.getText());
            pstmt.setString(7, txtPagerno.getText());
            pstmt.setString(8, cbxMaritalStatus.getSelectedItem().toString());
            pstmt.setInt(9, Integer.parseInt(txtNoofChildren.getText()));
            pstmt.setInt(10, Integer.parseInt(txtAnnualIncome.getText()));
            pstmt.setString(11, txtName.getText());
            
            pstmt.executeUpdate();
            DisplayData();
            GetAverageIncome();
            refreshForm();
            JOptionPane.showMessageDialog(this, "Data Updated Successfully!!");
            
        } catch(Exception ex){
            Logger.getLogger(RetailCompanyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        refreshForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try{
            qry = "delete from retailcompany where name=?";
            pstmt = con.prepareStatement(qry);
            pstmt.setString(1, txtName.getText());
            pstmt.executeUpdate();
            DisplayData();
            GetAverageIncome();
            refreshForm();
            JOptionPane.showMessageDialog(this, "Data Deleted Successfully!!");
            
        } catch(Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) RetailCompanyTable.getModel();
        if(txtSearch.getText() == null){
            DisplayData();
        }
        else{
           try{
               tblModel.setRowCount(0);
               qry = "select * from retailcompany where name=?";
               pstmt = con.prepareStatement(qry);
               pstmt.setString(1, txtSearch.getText());
               ResultSet rs = pstmt.executeQuery();
               
               while(rs.next()){
                   String name = rs.getString("name");
                   String home_address = rs.getString("home_address");
                   String home_phoneno = rs.getString("home_phoneno");
                   String business_address = rs.getString("business_address");
                   String business_phoneno = rs.getString("business_phoneno");
                   String faxmachineno = rs.getString("faxmachineno");
                   String cellular_phoneno = rs.getString("cellular_phoneno");
                   String pagerno = rs.getString("pagerno");
                   String merital_status = rs.getString("merital_status");
                   String no_of_children = String.valueOf(rs.getInt("no_of_childern"));
                   String annual_income = String.valueOf(rs.getInt("annual_income"));
                
                   String tableData[] = {name, home_address, home_phoneno, business_address, business_phoneno, faxmachineno, cellular_phoneno, pagerno, merital_status, no_of_children, annual_income};
                   tblModel.addRow(tableData);
                   System.out.println(Arrays.toString(tableData));
                   txtSearch.setText("");
               }
               
           } catch(Exception ex){
               System.out.println(ex);
           }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    
    private void DisplayData(){
        try {
            DefaultTableModel tblModel = (DefaultTableModel) RetailCompanyTable.getModel();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
            tblModel.setRowCount(0);
            
            PreparedStatement stmt = con1.prepareStatement("select * from retailcompany");
            ResultSet rs = stmt.executeQuery();
            
            while(rs.next()){
                String name = rs.getString("name");
                String home_address = rs.getString("home_address");
                String home_phoneno = rs.getString("home_phoneno");
                String business_address = rs.getString("business_address");
                String business_phoneno = rs.getString("business_phoneno");
                String faxmachineno = rs.getString("faxmachineno");
                String cellular_phoneno = rs.getString("cellular_phoneno");
                String pagerno = rs.getString("pagerno");
                String merital_status = rs.getString("merital_status");
                String no_of_children = String.valueOf(rs.getInt("no_of_childern"));
                String annual_income = String.valueOf(rs.getInt("annual_income"));
                
                String tableData[] = {name, home_address, home_phoneno, business_address, business_phoneno, faxmachineno, cellular_phoneno, pagerno, merital_status, no_of_children, annual_income};
                tblModel.addRow(tableData);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(RetailCompanyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void refreshForm()
    {
        txtName.setText("");
        txtHomeAddress.setText("");
        txtHomePhoneno.setText("");
        txtBusinessAddress.setText("");
        txtBusinessPhoneno.setText("");
        txtFaxMachineno.setText("");
        txtCellularPhoneno.setText("");
        txtPagerno.setText("");
        cbxMaritalStatus.setSelectedIndex(0);
        txtNoofChildren.setText("");
        txtAnnualIncome.setText("");
    }
    
    private void GetAverageIncome(){
        try{
             pstmt = con.prepareCall("CALL SP_Get_AverageIncome()");
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next()){
                String avgIncome = String.valueOf(rs.getInt("avgIncome"));
                txtAverageIncome.setText(avgIncome);
                System.out.println(avgIncome);
            }
            
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetailCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetailCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetailCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetailCompanyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetailCompanyForm().setVisible(true);
            }
        });
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "");
        } catch(Exception ex){
            System.out.println(ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RetailCompanyTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxMaritalStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAnnualIncome;
    private javax.swing.JLabel lblAverageIncome;
    private javax.swing.JLabel lblBusinessAddress;
    private javax.swing.JLabel lblBusinessPhoneno;
    private javax.swing.JLabel lblCellularPhoneno;
    private javax.swing.JLabel lblFaxMachineno;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblHomePhoneno;
    private javax.swing.JLabel lblMaritalStatus;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNoofChildren;
    private javax.swing.JLabel lblPagerno;
    private javax.swing.JTextField txtAnnualIncome;
    private javax.swing.JTextField txtAverageIncome;
    private javax.swing.JTextArea txtBusinessAddress;
    private javax.swing.JTextField txtBusinessPhoneno;
    private javax.swing.JTextField txtCellularPhoneno;
    private javax.swing.JTextField txtFaxMachineno;
    private javax.swing.JTextArea txtHomeAddress;
    private javax.swing.JTextField txtHomePhoneno;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNoofChildren;
    private javax.swing.JTextField txtPagerno;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
